<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="Home.aspx.cs" Inherits="KursovaRabota.Home" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
        <h2>Училище</h2>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
    <p class="success-box" style="margin-top: 0px; margin-right: 0px; margin-bottom: 3em !important; margin-left: 0px; padding: 1.9em 1em 1.7em 6.5em; border: 1px solid rgb(149, 148, 188); outline: 0px; font-size: 13px; vertical-align: baseline; background: rgb(216, 220, 243) url('http://slaveykov.net/images/icons/success-icon.png') no-repeat 20px center; line-height: 1.5em; border-radius: 12px; color: rgb(47, 47, 47); font-family: Tahoma, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: transparent;">В Основно училище „Петко Рачев Славейков“- град Варна се обучават ученици от първи до седми клас.</strong></p>
    <p class="arrow-box" style="margin-top: 0px; margin-right: 0px; margin-bottom: 3em !important; margin-left: 0px; padding: 1.9em 1em 1.7em 6.5em; border: 1px solid rgb(148, 184, 81); outline: 0px; font-size: 13px; vertical-align: baseline; background: rgb(225, 239, 182) url('http://slaveykov.net/images/icons/arrow-icon.png') no-repeat 20px center; line-height: 1.5em; border-radius: 12px; color: rgb(47, 47, 47); font-family: Tahoma, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: transparent;">За настоящата учебна година 2015/2016 броят на учениците е 1115, разпределени в 37 паралелки и ПГ – четири групи с 89&nbsp;ученици. Полуинтернатните групи са четири за І и ІІ клас.</strong></p>
    <strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: rgb(255, 255, 255); color: rgb(47, 47, 47); font-family: Tahoma, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">Провеждат се състезания, игри и викторини по всички предмети, в които те доказват своята отлична подготовка.Нашите ученици достойно защитават името на училището.</strong><p style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: rgb(255, 255, 255); line-height: 1.5em; color: rgb(47, 47, 47); font-family: Tahoma, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
    </p>
    <p style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: rgb(255, 255, 255); line-height: 1.5em; color: rgb(47, 47, 47); font-family: Tahoma, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        &nbsp;</p>
    <p style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: rgb(255, 255, 255); line-height: 1.5em; color: rgb(47, 47, 47); font-family: Tahoma, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <img alt="ОУ Петко Рачев Славейков - град Варна " src="http://www.slaveykov.net/wp-content/uploads/2014/07/more51.jpg" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: transparent;" width="100%" /><br />
        <img alt="ОУ Петко Рачев Славейков - град Варна " src="http://www.slaveykov.net/wp-content/uploads/2014/07/more61.jpg" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: transparent;" width="100%" /><br />
        <img alt="ОУ Петко Рачев Славейков - град Варна " src="http://www.slaveykov.net/wp-content/uploads/2014/07/more91.jpg" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: transparent;" width="100%" /><br />
        <img alt="ОУ Петко Рачев Славейков - град Варна " src="http://www.slaveykov.net/wp-content/uploads/2014/07/PC2000011.jpg" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: transparent;" width="100%" /><br />
        <img alt="ОУ Петко Рачев Славейков - град Варна " src="http://www.slaveykov.net/wp-content/uploads/2014/07/CIMG13171.jpg" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: transparent;" width="100%" /><br />
        <img alt="ОУ Петко Рачев Славейков - град Варна " src="http://www.slaveykov.net/wp-content/uploads/2014/07/CIMG13401.jpg" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: transparent;" width="100%" /></p>
</asp:Content>
