<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="WebForm1.aspx.cs" Inherits="KursovaRabota.WebForm1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h2>За нашия патрон</h2>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
    <p style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: rgb(255, 255, 255); line-height: 1.5em; color: rgb(47, 47, 47); font-family: Tahoma, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
    Петко Рачов Славейков е български поет, публицист, фолклорист и политик. Един от водачите на Либералната партия след Освобождението, той е председател на Народното събрание (1880) и министър в няколко кабинета (1880-1881, 1884-1885).</p>
<p style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: rgb(255, 255, 255); line-height: 1.5em; color: rgb(47, 47, 47); font-family: Tahoma, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
    Бащата на Петко също е наречен Рачо, но се заема с казанджийство. Той е слабо образован, но е с горд български дух. В селото на майка си, Вишовград, Петко вижда славеи, които го впечатляват дотолкова, че променя фамилията си на Славков.</p>
<div id="attachment_1478" class="wp-caption alignleft" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: rgb(255, 255, 255); float: left; color: rgb(47, 47, 47); font-family: Tahoma, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; max-width: 306px;">
    <img alt="Нашият патрон" class="size-full wp-image-1478" height="400" src="http://www.slaveykov.net/wp-content/uploads/1875/07/petkors.jpg" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: transparent;" width="296" /><p class="wp-caption-text" style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: transparent; line-height: 1.5em;">
        Нашият патрон</p>
</div>
<p style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: rgb(255, 255, 255); line-height: 1.5em; color: rgb(47, 47, 47); font-family: Tahoma, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
    П.Р.Славейков учи последователно във Велико Търново, Дряново, Трявна и Преображенския манастир. Независимо от това, усилено се самообразова с много четене в библиотеките на манастирите около Велико Търново. Голяма роля за образованието му изиграва и запознаването му с „История славянобългарска“ на Паисий Хилендарски. По-късно учи в Свищов (при Емануил Васкидович), разширява познанията си по гръцки и се запознава с произведения от сръбската и западноевропейската литература. Първото му литературно произведение – „Акатист на три светители“ – е запазено.</p>
<p style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: rgb(255, 255, 255); line-height: 1.5em; color: rgb(47, 47, 47); font-family: Tahoma, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
    Просветна и литературна дейност</p>
<p style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: rgb(255, 255, 255); line-height: 1.5em; color: rgb(47, 47, 47); font-family: Tahoma, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
    През 1843 г. Славейков става учител във Велико Търново, но за написаното „Прославило се Търново със славни гръцки владици е изгонен. От 1844 до 1864 г. последователно става учител в други села и градове – Видин, Враца, Плевен, Берковица, Лясковец, Бяла, Елена и др. Преподава по взаимоучителния метод като продължава да чете. Работи като учител в първото класно училище в Елена и му дава името Даскалоливницата (подобно на свещоливница, място където се леят даскали).<br />
    Корицата на „Смесена китка“, първо издание, 1852 година, Букурещ. Експонат на къща-музей „Иван Вазов“ в Берковица.</p>
<p style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: rgb(255, 255, 255); line-height: 1.5em; color: rgb(47, 47, 47); font-family: Tahoma, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
    Развива важна културно-просветна дейност и до 1847 г. събира 2263 песни, пословици и поговорки. Никола Михайловски го запознава с руските поети и писатели. От 1852 г. отпечатва първите си книги -„Смесена китка“, „Песнопойка“, „Басненик“. Пише поемата „Бойка войвода“ (1853) под влияние на революционните събития около Кримската война (1853-1856) и много бунтовни песни. Участва в заговора за неуспешното въстание на дядо Никола в Търново (1856). Като учител в Търговище издава български сатиричен вестник „Гайда“. След като работи известно време във Варна, заминава за Истанбул, поканен през 1864 г. да редактира българския превод на Библията (на източно българско наречие) от Българското библейско дружество, наред с Албърт Лонг, Илайъс Ригс и Христодул Сичан-Николов, чийто цялостен превод бил отпечатан през 1871 г. в Цариград. За значението на тяхното дело пише Пенчо Славейков:</p>
<p style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: rgb(255, 255, 255); line-height: 1.5em; color: rgb(47, 47, 47); font-family: Tahoma, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
    „Преводът на Библията тури край на езиковата безредица, на боричкането на разните наречия за първенство и се установи литературният език. След появяването на Библията на бял свят заглъхват разприте между разните български говори и източнобългарският говор става общ език за всички ратници на мисълта и националното съзнание.“</p>
<p style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: rgb(255, 255, 255); line-height: 1.5em; color: rgb(47, 47, 47); font-family: Tahoma, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
    Паметник на Пенчо и Петко Славейкови на площада в София, носещ тяхното име.</p>
<p style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: rgb(255, 255, 255); line-height: 1.5em; color: rgb(47, 47, 47); font-family: Tahoma, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
    В Цариград П. Р. Славейков издава вестник „Гайда“ (1863-1867), вестник „Македония“ (1866-1872), списание „Ружица“ (1871), сп. „Пчелица“ (1871), сп. „Читалище“ (1872-1873), „Звънчатий глумчо“ (1872), в. „Шутош“ (1873-1874), „Костурка“ (1874). Славейков се очертава като най-известният български писател по това време в Цариград. Издава повече от 60 книги, вестници и списания (оригинални и преводни). Взема участие в църковна борба и става един от ръководителите ѝ. По-късно е учител в българската екзархия. През 1873 г. създава известната поема „Изворът на белоногата“.</p>
<p style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: rgb(255, 255, 255); line-height: 1.5em; color: rgb(47, 47, 47); font-family: Tahoma, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
    За статията „Двете касти и власти“ (в. „Македония“) е арестуван и обвинен във връзки с революционния комитет в Букурещ.</p>
<p style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: rgb(255, 255, 255); line-height: 1.5em; color: rgb(47, 47, 47); font-family: Tahoma, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
    След пътуване до Македония, през 1874 г. Петко Славейков участва в основаването на българска гимназия в Одрин, където се бори с гръцкото влияние върху българите. По-късно е учител в Стара Загора, пише борчески стихотворения (1876), и за кратко отново е в затвора след Априлското въстание. След превземането на Стара Загора от руските войски през 1877 г. е назначен за председател на градската управа. При последвалото опожаряване на града загубва ръкописите си и събраните 15 000 пословици. През следващите месеци сътрудничи на руските войски, превежда през Стара планина отряда на генерал Михаил Скобелев, става свидетел на Шипченската победа и ги придружава до Сан Стефано.</p>
<p style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: rgb(255, 255, 255); line-height: 1.5em; color: rgb(47, 47, 47); font-family: Tahoma, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
    И в оригиналните, и в подражателните си творби П. Р. Славейков доразвива българския език. Пише исторически патриотични песни и поеми, любовна и пейзажна лирика под влияние на руските поети Александър Сергеевич Пушкин, Афанасий Фет и Николай Карамзин. Запазени са части от исторически патриотични поеми (написани най-вероятно под влияние на Паисиевата история – „Крумиада“, „Кралев Марко“, „Самуилка“). Издава два сборника с народни песни (1860, 1868), възстановява събраните пословици (17 000 на брой).</p>
<p style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: rgb(255, 255, 255); line-height: 1.5em; color: rgb(47, 47, 47); font-family: Tahoma, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
    Освен поет, писател и журналист, П. Р. Славейков остава в българската литература и като преводач, филолог, фолклорист, основоположник на българската литература за деца, автор на учебници; проявява се като географ, историк и мемоарист. Издава „Български притчи и пословици и характерни думи“, изследва българските обичаи, обредната система, демонологията и народопсихологията. Пише под множество псевдоними.</p>
<p style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: rgb(255, 255, 255); line-height: 1.5em; color: rgb(47, 47, 47); font-family: Tahoma, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
    През 1875 година Славейков става дописен, а през 1884 година – почетен член на Българското книжовно дружество, днес Българска академия на науките.</p>
<p style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: rgb(255, 255, 255); line-height: 1.5em; color: rgb(47, 47, 47); font-family: Tahoma, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
    Политическа дейност:</p>
<p style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: rgb(255, 255, 255); line-height: 1.5em; color: rgb(47, 47, 47); font-family: Tahoma, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
    След Освобождението Петко Славейков става един от водачите на новообразуваната Либерална партия. Става председател на Народното събрание (1880), министър на народното просвещение (1880) и министър на вътрешните работи (1880-1881) в правителството на Петко Каравелов. По време на Режима на пълномощията (1881-1883) заминава за Пловдив, където преподава в Пловдивската гимназия. След завръщането си в България отново е вътрешен министър (1884-1885) в новия кабинет</p>
<p style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: rgb(255, 255, 255); line-height: 1.5em; color: rgb(47, 47, 47); font-family: Tahoma, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
    Издава в. „Остен“ (1879), в. „Целокупна България“ (1879), в. „Независимост“ 1880-1883), в. „Търновска конституция“ (1884), в. „Истина“ (1886), в. „Софийски дневник“ (1886) и в. „Правда“ (1888).</p>
<p style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: rgb(255, 255, 255); line-height: 1.5em; color: rgb(47, 47, 47); font-family: Tahoma, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
    За подчертани демократични идеи и участие в политическите борби е арестуван, забранено му е да учителствува и му намаляват пенсията.</p>
<p style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: rgb(255, 255, 255); line-height: 1.5em; color: rgb(47, 47, 47); font-family: Tahoma, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
    Петко Славейков умира в София на 1 юли 1895 г.</p>
</asp:Content>
