<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="Work.aspx.cs" Inherits="KursovaRabota.Work" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h2>Биография и Творчество</h2>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
    <div id="attachment_777" class="wp-caption alignleft" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: rgb(255, 255, 255); float: left; color: rgb(47, 47, 47); font-family: Tahoma, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; max-width: 310px;">
        <img alt="Петко Рачов Славейков" src="http://www.slaveykov.net/wp-content/uploads/1875/07/petkors.jpg" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: transparent;" width="300" /><p class="wp-caption-text" style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: transparent; line-height: 1.5em;">
            Петко Рачов Славейков</p>
    </div>
    <p style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: rgb(255, 255, 255); line-height: 1.5em; color: rgb(47, 47, 47); font-family: Tahoma, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <strong style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: transparent;">Биография и Творчество на Петко Рачов Славейков</strong></p>
    <p style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: rgb(255, 255, 255); line-height: 1.5em; color: rgb(47, 47, 47); font-family: Tahoma, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        Роден на 17.11.1827 г. в Търново, в дома на Рачо Казанджията – в стар занаятчийски род Петко Рачов Славейков израства в семейство с горд български дух. Бащата е слабо образован, но поддържа сина си да учи последователно в Търново, Дряново, Трявна и Преображенския манастир. Петко Славейков усилено се самообразова с много четене в библиотеките на манастирите около Търново и региона.</p>
    <p style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: rgb(255, 255, 255); line-height: 1.5em; color: rgb(47, 47, 47); font-family: Tahoma, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        Голяма роля за образованието му изиграва и запознаването му с „История славянобългарска“ на Паисий Хилендарски. По-късно учи в Свищов (при Е. Васкидович), разширява познанията си по гръцки и се запознава с произведения от сръбската и западноевропейската литература. Първото му литературно произведение – „Акатист на три светители“ -е запазено. През 1843 г. става учител в Търново. Но за написаното „Прославило се Търново със славни гръцки владици“ е изгонен и последователно става учител в други села и градове – Видин, Враца, Плевен, Берковица, Лясковец, Бяла, Елена и др. Преподава по взаимо-учителния метод като продължава да чете. Развива важна културно-просветна дейност и до 1847 г. събира 2263 песни, пословици и поговорки.Н. Михайловски го запознава с руските поети и писатели. От 1852 г. отпечатва първите си книги – „Смесена китка“, „Песнопойка“, „Басненик“.</p>
    <p style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: rgb(255, 255, 255); line-height: 1.5em; color: rgb(47, 47, 47); font-family: Tahoma, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        Пише поемата „Бойка войвода“ (1853) под влияние на революционните събития около Кримската война (1853-1856) и много бунтовни песни. След неуспешното въстание на дядо Никола в Търново П. Р. Славейков насочва усилията си към пробуждане на националното съзнание. Като учител в Търговище издава български сатиричен вестник „Гайда“. След като работи известно време във Варна, заминава за Цариград, поканен да редактира българския превод на Библията от Българското библейско дружество наред с А. Лонг, Ел. Ригс, Хр. К. Сичан-Николов.В Цариград П. Р. Славейков издава вестник „Гайда“ (1863-1867), вестник „Македония“ (1866-1872), списание „Ружица“ (1871), сп. „Пчелица“ (1871), сп. „Читалище“ (1872-1873), „Звънчатий глумчо“ (1872), в. „Шутош“ (1873-1874), „Костурка“ (1874).</p>
    <p style="margin: 0px 0px 1.5em; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: rgb(255, 255, 255); line-height: 1.5em; color: rgb(47, 47, 47); font-family: Tahoma, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <i style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-size: 13px; vertical-align: baseline; background: transparent;">Славейков се очертава като най-известният български писател по това време в Цариград. Издава повече от 60 книги, вестници и списания (оригинални и преводни). Взема участие в черковната борба и става един от ръководителите й. По-късно бива учител в българската Екзархия.За статията „Двете касти и власти“ (в. „Македония“) е арестуван и обвинен във връзки с революционния комитет в Букурещ.</i></p>
</asp:Content>
